DROP DATABASE IF EXISTS testdb;

CREATE DATABASE testdb;

DROP USER IF EXISTS testuser;

CREATE USER testuser WITH ENCRYPTED PASSWORD 'testpassword';

GRANT ALL PRIVILEGES ON DATABASE testdb TO testuser;
